sudo: required
services:
  - docker
env:
  global:
    - REGISTRY_USER=myrobot
    # REGISTRY_PASS=...
    - secret: "<something long>"

before_script:
  - docker pull myorg/myimage || true
script:
  - docker build --pull --cache-from myorg/myimage --tag myorg/myimage .
  - docker run myorg/myimage

after_script:
  - docker images

before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push myorg/myimage
  on:
    branch: master